use_frameworks!

target 'Stickers_Example' do
  pod 'Stickers', :path => '../'
  
  pod 'Kingfisher', '~> 4.6.3'
  pod 'NVActivityIndicatorView', '~> 4.1.1'
  target 'Stickers_Tests' do
    inherit! :search_paths

    
  end
end
